version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-loginapp
    restart: unless-stopped
    environment:
      POSTGRES_DB: loginapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: 